// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2zlivIsUnUg1b1CjiAyN6FFJWGROZGNo',
    appId: '1:547867534005:web:c72d2cf4505f3b137814fc',
    messagingSenderId: '547867534005',
    projectId: 'clone-9b337',
    authDomain: 'clone-9b337.firebaseapp.com',
    storageBucket: 'clone-9b337.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeotPt-SyEHwc1KvRsjRm9Q_syY9dQyEI',
    appId: '1:547867534005:android:987ed09f4c5c1ed37814fc',
    messagingSenderId: '547867534005',
    projectId: 'clone-9b337',
    storageBucket: 'clone-9b337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8nSwisgk7-GJlPuKfgo5fynzC2qG1b9w',
    appId: '1:547867534005:ios:06d9e71cf7e8b2637814fc',
    messagingSenderId: '547867534005',
    projectId: 'clone-9b337',
    storageBucket: 'clone-9b337.appspot.com',
    iosClientId: '547867534005-bu7592ochvrifgu4hsnoi419v54mdba6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokTutorial',
  );
}
